---
apiVersion: v1
kind: Service
metadata:
  # Headless service is not backed-up by ClusterIP, thus it points to the IP of all the Pods it is backing.
  # This property is used as a service discovery mechanism.
  name: redis-headless
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
