apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - master/application.yaml
  - master/service.yaml
  - replicas/statefulset.yaml
  - replicas/service.yaml
  - configmap.yaml
  - headless-svc.yaml
  - health-configmap.yaml
  - scripts-configmap.yaml
  - secret.yaml
  - serviceaccount.yaml

images:
  - name: redis
    newName: docker.io/bitnami/redis
    newTag: 7.2.2-debian-11-r0
