---
# Source: redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-redis
  namespace: "dev-enablement"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.2.2
    helm.sh/chart: redis-18.1.6
type: Opaque
data:
  redis-password: "UFh0bzFWNEFnYg=="
