---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    component: master
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
    component: master
