apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ssh://github.com/utilitywarehouse/shared-kustomize-bases//redis/manifests/dev-enablement/redis-shared?ref=v0.0.0

secretGenerator:
  - name: redis
    envs:
      - secrets/redis-secret.txt
    options:
      disableNameSuffixHash: true
