apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml

patches:
  # remove these empty affinity nodes, as in Kustomize 5.0.x kustomize generates them as strings with value "null" instead of just null, and they can not be applied.
  # added this issue in kustomize: https://github.com/kubernetes-sigs/kustomize/issues/5171
  - patch: |-
      - op: remove
        path: /spec/template/spec/affinity/podAffinity
      - op: remove
        path: /spec/template/spec/affinity/nodeAffinity
    target:
      group: apps
      version: v1
      kind: StatefulSet
